### ISSUE TITLE
在做一个winedt 11.0的汉化包

### ISSUE THREAD

**Issue by twahz** [maboloshi/WinEdt-10-User-Settings#2]
在做一个winedt 11.0的汉化包

**Comment by maboloshi** [comment]
感谢 提醒 这软件终于更新了 我有时间再看看winedt 11.0的情况

**Comment by twahz** [comment]
winedt 11.0 key
name：*60[20220501] Warez_Down [RU-BOARD] (100 users)
code：4049089118892183088

**Comment by maboloshi** [comment]
已经初步迁移 https://github.com/maboloshi/WinEdt-11-User-Settings
